### ISSUE TITLE
Missing protocol version in error about unknown protocol version

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog-plugin-beats#14]
Just upgraded to 1.1.2 and got error:

```
java.lang.Exception: Unknown beats protocol version: {}
        at org.graylog.plugins.beats.BeatsFrameDecoder.checkVersion(BeatsFrameDecoder.java:155) ~[?:?]
```

According to sources, there is missing format argument.
Also strange thing is that I've got this error only once... Maybe some network error.

**Comment by joschi** [comment]
@hc4 Which beat are you using and in which version?

**Comment by hc4** [comment]
I'm using filebeat and topbeat same version on every host. But got error only once :)
So the problem sure not in beats

**Comment by joschi** [comment]
@hc4

> I'm using filebeat and topbeat same version on every host.

And the version being…?

Additionally, please attach the configuration for each beat and the configuration of your Beats input.

**Comment by hc4** [comment]
1.2.3

**Comment by joschi** [comment]
@hc4 And the configuration for each beat and the configuration of your Beats input…

**Comment by hc4** [comment]
I'll check configs on monday.
Looked in code and have a question.
Shouldn't  [there ](https://github.com/Graylog2/graylog-plugin-beats/blob/master/src/main/java/org/graylog/plugins/beats/BeatsFrameDecoder.java#L82) be a break after line 82?

**Comment by hc4** [comment]
Filebeat output config:

```
  logstash:
    hosts: ["1.1.1.1:5044", "2.2.2.2:5044"]
    max_retries: -1
    tls:
      certificate_authorities: ["pem file"]
      insecure: false
```

Beats input:

```
{
 "title": "Beats TLS",
 "global": false,
 "name": "Beats",
 "content_pack": null,
 "created_at": "2016-10-14T09:33:24.342Z",
 "type": "org.graylog.plugins.beats.BeatsInput",
 "creator_user_id": "user id",
 "attributes": {
   "recv_buffer_size": 212992,
   "port": 5044,
   "tls_key_file": "key8 file",
   "tls_enable": true,
   "tls_key_password": "key pass",
   "tcp_keepalive": false,
   "tls_client_auth_cert_file": "",
   "tls_client_auth": "disabled",
   "override_source": "",
   "bind_address": "0.0.0.0",
   "tls_cert_file": "crt file"
 },
 "static_fields": {},
 "node": "node id",
 "id": "input id"
}
```

**Comment by joschi** [comment]
@hc4 

> Filebeat output config:

That's not the complete configuration. Please provide the _complete_ configuration of both of your beats…

**Comment by hc4** [comment]
which section exactly do you need?
Configs may contain some sensitive information.
e.g. I'm not sure if you need prospectors config

**Comment by hc4** [comment]
```
filebeat:
  registry_file: registry
  config_dir: config dir
output:
  logstash:
    hosts: ["1.1.1.1:5044", "2.2.2.2:5044"]
    max_retries: -1
    tls:
      certificate_authorities: ["pem file"]
      insecure: false
shipper:
logging:
  to_files: true
  files:
    path: logs path
    rotateeverybytes: 10485760 # = 10MB
    keepfiles: 7
  selectors: ["*"]
  level: info
```
